- name: Azure SQL Deploy
  uses: Azure/sql-action@v2.2
  with:
    # The connection string, including authentication information, for the Azure SQL Server database.
    connection-string: 
    # Path to the file used for this action. Supported file types are .sql, .dacpac, or .sqlproj.
    path: 
    # If not using a .sql file, the sqlpackage action to execute.
    action: # optional
    # In case of .dacpac or .sqlproj file types, additional sqlpackage arguments that will be applied. In case of .sql file type, additional go-sqlcmd argument that will be applied.
    arguments: # optional
    # In case of a .sqlproj file, additional arguments that will be applied to dotnet build when building the database project.
    build-arguments: # optional
